from typing import Optional, List

from ..model import TrackJson


class BaseTracks:
    def get_track(self, *args, **kwargs) -> Optional[TrackJson]: ...
    def get_tracks(self, *args, **kwargs) -> List[TrackJson]: ...
    @property
    def size(self) -> int: ...
    @property
    def tracks(self) -> List[TrackJson]: ...
