from typing import Dict


class AttrDict(dict):
    def __init__(self, seq: Dict = None, **kwargs): ...
    def __repr__(self): ...
    def __setitem__(self, key, value): ...
    def __setattr__(self, key, value): ...
    def __getattr__(self, item): ...
    def __update(self): ...
    def update(self, seq: Dict = None, **kwargs): ...
    def copy(self, **kwargs) -> AttrDict: ...
