from typing import Mapping, TypeVar

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")


class AttrDict(dict):
    def __init__(self, seq=None, **kwargs):...
    def update(self, __m: Mapping[_KT, _VT] = None, **kwargs: _VT):...
    def __setattr__(self, key, value):...
    def __getattr__(self, item):...
    def __bool__(self):...
    @property
    def size(self) -> int:...
    def copy(self) -> AttrDict:...
