from pathlib import Path

from ..model import ConfigJson


class Config(ConfigJson):
    def __init__(self, root_folder: Path): ...
    def _check_config(self): ...
    def _set_log_dir(self, root_folder: Path): ...
    @classmethod
    def get_config_folder(cls, root_folder: Path) -> Path: ...
    @classmethod
    def get_json_folder(cls, root_folder: Path) -> Path: ...
    @classmethod
    def get_modules_folder(cls, root_folder: Path) -> Path: ...
