from pathlib import Path
from typing import Dict, Any

T = Dict[str, Any]

class Migrate:
    _root_folder: Path

    def __init__(self, root_folder: Path): ...
    @staticmethod
    def _config_0_1(old_config: T) -> T: ...
    @staticmethod
    def _config_1_2(old_config: T) -> T: ...
    @staticmethod
    def _config_new(old_config: T) -> T: ...
    def config(self): ...
    def track(self): ...