from pathlib import Path
from typing import Optional, List

from .RepoConfig import RepoConfig
from ..model import *
from ..utils import Log


class RepoPull:
    _log: Log
    _modules_folder: Path
    _local_folder: Path

    _tracks: List[TrackJson]
    _repo_url: str
    _max_num: int

    json_file: Path
    timestamp: float
    modules_json: ModulesJson

    def __init__(self, tracks: List[TrackJson], root_folder: Path, config: RepoConfig): ...
    def _get_temp_file(self, module_id: str) -> Path: ...
    def _get_zip_file(self, module: OnlineModule) -> Path: ...
    def _get_file_url(self, module_id: str, file: Path) -> str: ...
    def _pull_from_zip_common(self, local_module: LocalModule, zip_file: Path, changelog: Optional[Path], *, delete_tmp: bool) -> OnlineModule: ...
    def pull_from_json(self, track: TrackJson) -> OnlineModule: ...
    def pull_from_url(self, track: TrackJson) -> OnlineModule: ...
    def pull_from_git(self, track: TrackJson) -> OnlineModule: ...
    def pull_from_zip(self, track: TrackJson) -> OnlineModule: ...
    def pull_from_track(self, track: TrackJson) -> OnlineModule: ...
    def pull_all(self): ...
